linters:
  CapitalizationInSelector:
    enabled: false

  Indentation:
    enabled: true
    character: space
    width: 4

  SelectorDepth:
    max_depth: 5

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  PropertySortOrder:
    enabled: false

  Compass::*:
    enabled: true
